/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2018-12-15 12:32:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/Css/main.css", Long.valueOf(1544734724000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1543615010000L));
    _jspx_dependants.put("/WEB-INF/Css/register.css", Long.valueOf(1544840346000L));
    _jspx_dependants.put("jar:file:/C:/Users/eskan/IdeaProjects/Github/Hospital/apache-tomcat-9.0.13/webapps/Hospital/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Reg</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        ");
      out.write("body{\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container{\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-areas: \"header header header\"\r\n");
      out.write("\t                     \"left main right\" \r\n");
      out.write("\t                     \"footer footer footer\";\r\n");
      out.write("\tgrid-template-columns: 1fr 9fr 1fr;\r\n");
      out.write("\tgrid-template-rows:    1fr 9fr 1fr;\r\n");
      out.write("\tmin-height:auto;\r\n");
      out.write("\tgrid-gap: 0px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".header{\r\n");
      out.write("\tgrid-area: header;\r\n");
      out.write("\tbackground: #fff1c8;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\t/*grid-template-columns: 400px;\r\n");
      out.write("\tgrid-template-rows: 400px*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main{\t\r\n");
      out.write("\tgrid-area: main;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\t/*grid-template: 300px 1fr 500px/300px 1fr 300px;*/\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tgrid-template-rows: 0.5fr;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content{\r\n");
      out.write("\tgrid-area: content;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer{\r\n");
      out.write("\tgrid-area: footer;\r\n");
      out.write("\tbackground: rgb(39,37,31);\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bigGrid{\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\theight: 480px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("\r\n");
      out.write("\tgrid-template-areas: \"myGrid  smallGrida smallGridc\"\r\n");
      out.write("\t                     \"myGrid  smallGridb smallGridd\" ;\r\n");
      out.write("\r\n");
      out.write("\tgrid-template-columns: 2fr 1fr 1fr;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".myGrid{\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-area: myGrid;\r\n");
      out.write("\r\n");
      out.write("\tbackground: #000;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\t/*grid-template-areas: \"smalltablea smalltablec\"\r\n");
      out.write("\t                     \"smalltableb smalltabled\" ;*/\r\n");
      out.write("\tgrid-template-rows: 2fr;\r\n");
      out.write("\tbackground-image: url(\"https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2018/09/24/18/44/home-young-boy-outside-6col-3663200-0024r.jpg\");\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write("\t                     \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*.table img{\r\n");
      out.write("\theight: 100%\r\n");
      out.write("\tweight: 100%;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write(".smallGrid{\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tgrid-template-rows: 0.25fr;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".smallGrid p{\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("    margin-top: 36%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a{\r\n");
      out.write("\tgrid-area: smallGrida;\r\n");
      out.write("\tbackground: rgb(0,61,165);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".b{\r\n");
      out.write("\tgrid-area: smallGridb;\r\n");
      out.write("\tbackground: rgb(51,100,183)\r\n");
      out.write("}\r\n");
      out.write(".c{\r\n");
      out.write("\tgrid-area: smallGridc;\r\n");
      out.write("\tbackground: rgb(25,80,174)\r\n");
      out.write("}\r\n");
      out.write(".d{\r\n");
      out.write("\tgrid-area: smallGridd;\r\n");
      out.write("\tbackground: rgb(76,119, 192)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.button1 {\r\n");
      out.write("  background: #678;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-weight: 300;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  user-select: none;\r\n");
      out.write("  padding: .5em 1.6em;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  border: 2px solid;\r\n");
      out.write("  border-radius: 1px;\r\n");
      out.write("  transition: 0.2s;\r\n");
      out.write("} \r\n");
      out.write("a.button1:hover { background: rgba(0,0,0,.8); }\r\n");
      out.write("a.button1:active { background: blue; }\r\n");
      out.write("\r\n");
      out.write("a.button2{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("    right: 0px;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.button3{\r\n");
      out.write("\tright: 140px;\r\n");
      out.write("\tpadding: .5em 2.75em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".context{\r\n");
      out.write(" display: flex;\r\n");
      out.write(" flex-wrap: wrap;\r\n");
      out.write("/*margin-right: 30px;*/\r\n");
      out.write(" justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".block{\r\n");
      out.write("   position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    /*margin-bottom: 30px;*/\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    box-shadow: 0px 0px 25px rgba(116, 116, 116, 0.25);\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 328px;\r\n");
      out.write("    /*padding: 30px 30px;*/\r\n");
      out.write("    margin-bottom: 18px;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".a1{\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a1 div{\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\tpadding-top: 46px;\r\n");
      out.write("\talign-self: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a1 img{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".a1 p{\r\n");
      out.write("\tfont-size: 19.5px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a2 p{\r\n");
      out.write("\tfont-size: 19.5px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t/*align-self: center;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c1 {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".c1 img{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write(".register_form{\r\n");
      out.write("  grid-area: divr;\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  align-items:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register_input{\r\n");
      out.write("box-sizing: border-box;\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  -moz-box-sizing: border-box;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  padding: 7px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-bottom: 1px solid #ddd;\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  height: 45px;\r\n");
      out.write("  -webkit-appearance: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".normalize{\r\n");
      out.write("  height: 100vh;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header{\r\n");
      out.write("background-color: rgb(39,37,31);\r\n");
      out.write("\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container normalize\">\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        Header\r\n");
      out.write("    </header>\r\n");
      out.write("    <aside class=\"left\"></aside>\r\n");
      out.write("    <aside class=\"right\"></aside>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"register_form\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <h2>Registration</h2>\r\n");
      out.write("            <form method=\"post\" action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\"  required placeholder=\"login\" name=\"login\"><br>\r\n");
      out.write("                <input type=\"password\"  required placeholder=\"password\" name=\"password\"><br>\r\n");
      out.write("                <input type=\"text\"  required placeholder=\"Name\" name=\"name\"><br>\r\n");
      out.write("                <input type=\"text\"  required placeholder=\"Birthday : YY-MM-DD\" name=\"birthday\"><br>\r\n");
      out.write("                <input type=\"text\"  required placeholder=\"Phone\" name=\"phone\"><br>\r\n");
      out.write("                <input type=\"hidden\"  name=\"role\"  value=\"P\"><br><br>\r\n");
      out.write("                <input class=\"button1\" class=\"register_input\" type=\"submit\" value=\"Rgestrate\">\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer\">Footer</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/view/Reg.jsp(31,40) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/add");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
